package polkammart;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Transaksi extends javax.swing.JInternalFrame {
    private DefaultTableModel model;
    public Statement st;
    public ResultSet rs;
    Connection cn = polkammart.Koneksi.getKoneksi();
    //public long bayarr;
    //public long totall;

    public Transaksi() {
        initComponents();
        TampilData();
        Judul();
        Reset();
        kd_transaksi();
        Barang();
        //kd_barcode();
     
        KodeTransaksi.setEnabled(false);
        Barcode.setEnabled(false);
        Harga.setEnabled(false);
        Stok.setEnabled(false);
        Tambah.setEnabled(false);
        Kembalian.setEnabled(false);
        Selesai.setEnabled(false);
    }
        
   private void TampilData(){
        try {
            st = cn.createStatement();
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            rs = st.executeQuery("select * from keranjang");
            while (rs.next()){
                Object[] data = {
                    rs.getString("nama_barang"),
                    rs.getString("harga_barang"),
                    rs.getString("jumlah_barang"),
                    rs.getString("harga")
                };
                model.addRow(data);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
   
    public void Judul(){
        Object[] judul = {"Nama Barang","Harga Barang","Jumlah Barang","Harga"};
        model = new DefaultTableModel(null, judul);
        tabelbarang.setModel(model);
    }
    
    private void Reset(){
         Barcode.setText("");
         NamaBarang.setSelectedItem(null);
         HargaBarang.setText("");
         Stok.setText("");
         JumlahBarang.setText("");
         Harga.setText("");
         KodeTransaksi.setText("");
     }
    
    private void kd_transaksi(){ 
        try{
            java.util.Date tgl = new java.util.Date();
            java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("yyMMdd");
            java.text.SimpleDateFormat tanggal = new java.text.SimpleDateFormat("yyyyMMdd");
            
            String sql = "Select max(no_transaksi) from transaksi where tanggal =" + tanggal.format(tgl);
            st = cn.createStatement();
            rs = st.executeQuery(sql);
            while(rs.next()){
                Long a = rs.getLong(1);
                if (a == 0) {
                    this.KodeTransaksi.setText(kal.format(tgl)+"0000"+(a+1));
                } else {
                    this.KodeTransaksi.setText(""+(a+1));
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
        
    public void Barang(){
        NamaBarang.removeAllItems();
        NamaBarang.addItem("Pilih Barang");
        try {
            st = cn.createStatement();
            rs = st.executeQuery("select * from barang");
            while (rs.next()) {
                NamaBarang.addItem(rs.getString("nama_barang"));
            }
        } catch (Exception e) { 
            e.printStackTrace();
        }
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Hapus = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        JumlahBarang = new javax.swing.JTextField();
        Stok = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Total = new javax.swing.JTextField();
        HargaBarang = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        KodeTransaksi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Selesai = new javax.swing.JButton();
        Kembalian = new javax.swing.JTextField();
        Hitung = new javax.swing.JButton();
        Pembayaran = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Barcode = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Tambah = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NamaBarang = new javax.swing.JComboBox();
        Harga = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelbarang = new javax.swing.JTable();

        setBackground(new java.awt.Color(153, 0, 153));
        setTitle("Transaksi");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        Hapus.setText("HAPUS");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nama Barang");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/program_kasir_untuk_pemula2.jpg"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel8.setText("TRANSAKSI");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Kode Transaksi");

        JumlahBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JumlahBarangKeyTyped(evt);
            }
        });

        Stok.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Barcode");

        HargaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HargaBarangActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Kembalian");

        KodeTransaksi.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Total");

        Selesai.setText("SELESAI");
        Selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelesaiActionPerformed(evt);
            }
        });

        Hitung.setText("HITUNG");
        Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungActionPerformed(evt);
            }
        });

        Pembayaran.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PembayaranKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Harga Barang");

        Barcode.setBackground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Stok");

        Tambah.setText("TAMBAH");
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Harga");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Jumlah Barang");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Pembayaran");

        NamaBarang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        NamaBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaBarangActionPerformed(evt);
            }
        });

        Harga.setBackground(new java.awt.Color(0, 0, 0));
        Harga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                HargaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel11))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Stok, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JumlahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(NamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Harga, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Hitung)
                                        .addGap(95, 95, 95)
                                        .addComponent(Tambah)
                                        .addGap(27, 27, 27))
                                    .addComponent(jLabel12))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(69, 69, 69)
                                        .addComponent(Hapus)
                                        .addGap(69, 69, 69)
                                        .addComponent(Selesai))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel5))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(KodeTransaksi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(Pembayaran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Barcode, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(NamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HargaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Stok, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JumlahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(KodeTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7))
                            .addGap(17, 17, 17)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addGap(33, 33, 33)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Selesai)
                                .addComponent(Hapus)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Hitung)
                            .addComponent(Tambah))
                        .addGap(4, 4, 4)
                        .addComponent(jLabel10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Harga, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        tabelbarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelbarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelbarangMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelbarang);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahActionPerformed
        // TODO add your handling code here:
       if("".equals(JumlahBarang.getText())){
            JOptionPane.showMessageDialog(null, "Lengkapi Data!");
        }else{
             try {
            st=cn.createStatement();
            st.executeUpdate("insert into keranjang set " + " nama_barang ='" + NamaBarang.getSelectedItem()
                    + "', harga_barang = '" + HargaBarang.getText() + "', jumlah_barang = '" 
                    + JumlahBarang.getText() + "', harga = '" + Harga.getText() + "';");
                TampilData();
                Reset();
                                  
            int total = 0;
                 for (int i = 0; i < tabelbarang.getRowCount(); i++) {
                     int amount = Integer.parseInt((String)tabelbarang.getValueAt(i, 3));
                     total += amount;
                 }
                 this.Total.setText("" + total);
                 
            JOptionPane.showMessageDialog(null, "Berhasil");
        } catch (Exception e) {
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_TambahActionPerformed

    private void HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungActionPerformed
        // TODO add your handling code here:
        if("".equals(HargaBarang.getText())||"".equals(Stok.getText())||"".equals(JumlahBarang.getText())){
            JOptionPane.showMessageDialog(null, "Lengkapi Data Anda");
        }else{
            Integer jumlah = Integer.parseInt(JumlahBarang.getText());
            Integer stok = Integer.parseInt(this.Stok.getText());
            if (jumlah > stok){
                JOptionPane.showMessageDialog(null, "Stok Hanya Ada "+stok);
            }else{
                int a = Integer.parseInt(HargaBarang.getText());
        int b = Integer.parseInt(JumlahBarang.getText());
        int hitung = a * b;
        Harga.setText(""+hitung);
        Tambah.setEnabled(true);
        Hitung.setEnabled(true);
            }   
        }
    }//GEN-LAST:event_HitungActionPerformed

    private void HargaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HargaBarangActionPerformed
        // TODO add your handling code here:
        try {
            HargaBarang.setText("");
            st = cn.createStatement();
            rs = st.executeQuery("select * from barang where harga_barang = '"+ HargaBarang.getText() +"'");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_HargaBarangActionPerformed

    private void NamaBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaBarangActionPerformed
        // TODO add your handling code here:
        try {
            HargaBarang.setText("");
            Stok.setText("");
            st = cn.createStatement();
            rs = st.executeQuery("select * from barang where nama_barang = '"+ NamaBarang.getSelectedItem() +"'");
            while (rs.next()) {
                if ("Pilih Barang".equals(NamaBarang.getSelectedItem())) {
                    HargaBarang.setText("");
                    Stok.setText("");
                } else {
                    Barcode.setText(rs.getString("barcode"));
                    HargaBarang.setText(rs.getString("harga"));
                    Stok.setText(rs.getString("stok"));
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_NamaBarangActionPerformed

    private void JumlahBarangKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JumlahBarangKeyTyped
        // TODO add your handling code here:
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_JumlahBarangKeyTyped

    private void tabelbarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelbarangMouseClicked
        // TODO add your handling code here:
        NamaBarang.setSelectedItem(model.getValueAt(tabelbarang.getSelectedRow(), 0)+ "");
        HargaBarang.setText(model.getValueAt(tabelbarang.getSelectedRow(), 1)+ "");
        JumlahBarang.setText(model.getValueAt(tabelbarang.getSelectedRow(), 2) + "");
        Harga.setText(model.getValueAt(tabelbarang.getSelectedRow(), 3) + "");
    }//GEN-LAST:event_tabelbarangMouseClicked

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
        try {
                int jawab;
                if ((jawab=JOptionPane.showConfirmDialog(null,"Hapus ?","konfirmasi",JOptionPane.YES_NO_OPTION))==0) {
                    st.executeUpdate("delete from barang where "+"barcode='"+model.getValueAt(tabelbarang.getSelectedRow(),0)+"'");
                    TampilData();
                    Reset();
                    JOptionPane.showMessageDialog(null, "Berhasil dihapus");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Gagal diHapus! "+e.getMessage());
            }
    }//GEN-LAST:event_HapusActionPerformed

    private void PembayaranKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PembayaranKeyReleased
        // TODO add your handling code here:
        int kmbl = 0;
        kmbl = Integer.parseInt(Pembayaran.getText())-Integer.parseInt(Total.getText());
        Kembalian.setText(String.valueOf(kmbl));
    }//GEN-LAST:event_PembayaranKeyReleased

    private void SelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelesaiActionPerformed
        // TODO add your handling code here:
//        try{
//            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
//	        LocalDateTime now = LocalDateTime.now();
//            int total = 0;
//            st = cn.createStatement();
//            rs = st.executeQuery("select * from keranjang");
//            while (rs.next()) {
//                total = total + Integer.parseInt(rs.getString("harga"));
//            }
//            bayarr = Integer.parseInt(Pembayaran.getText());
//            totall = Integer.parseInt(this.Total.getText());
//            if(bayarr < totall) {
//                JOptionPane.showMessageDialog(null, "Uang Anda Kurang");
//            }else{
//         
//            int kmbl = Integer.parseInt(Pembayaran.getText()) - total;
//            st.executeUpdate("insert into transaksi values('"+KodeTransaksi.getText()+"','"+Barcode.getText()+"','"+total+"','"+Integer.parseInt(Pembayaran.getText())+"','"+Kembalian.getText()+"','"+now+"')");
//            try {
//                Desktop.getDesktop().browse(new URL("http://localhost:81/laporan/struk.php?id="+KodeTransaksi.getText()).toURI());
//            } catch (IOException ex) {
//                Logger.getLogger(transaksi.class.getName()).log(Level.SEVERE, null, ex);
//            } catch (URISyntaxException ex) {
//                Logger.getLogger(transaksi.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            }
//            try {
//            int jawab = 0;
//            if ((jawab = JOptionPane.showConfirmDialog(null, "Yakin ingin mengakhiri belanja?", "Konfirmasi", JOptionPane.YES_NO_OPTION))==0) {
//                String sql = "Truncate keranjang";
//            st = cn.createStatement();
//            st.executeUpdate(sql);
//            TampilData();
//            kd_transaksi();
//            this.Total.getText();
//            Pembayaran.setText("");
//            Kembalian.setText("");
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, e.getMessage());
//        }
//        }catch(Exception e){
//            JOptionPane.showMessageDialog(null, e.getMessage());
//        }
    }//GEN-LAST:event_SelesaiActionPerformed

    private void HargaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HargaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_HargaKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Barcode;
    private javax.swing.JButton Hapus;
    private javax.swing.JTextField Harga;
    private javax.swing.JTextField HargaBarang;
    private javax.swing.JButton Hitung;
    private javax.swing.JTextField JumlahBarang;
    private javax.swing.JTextField Kembalian;
    private javax.swing.JTextField KodeTransaksi;
    private javax.swing.JComboBox NamaBarang;
    private javax.swing.JTextField Pembayaran;
    private javax.swing.JButton Selesai;
    private javax.swing.JTextField Stok;
    private javax.swing.JButton Tambah;
    private javax.swing.JTextField Total;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabelbarang;
    // End of variables declaration//GEN-END:variables
}
